version: 2

updates:
  - package-ecosystem: npm
    directory: /site
    schedule:
      interval: monthly
    groups:
      site-dependencies:
        patterns: ["*"]
    open-pull-requests-limit: 1
    rebase-strategy: disabled
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: deps

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns: ["*"]
    open-pull-requests-limit: 1
    rebase-strategy: disabled
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: deps
