from __future__ import annotations

from pathlib import Path

import pytest
from tests.test_resolver import MATRIX

from rigsolve.cli import main


def matrix_file(tmp_path: Path) -> Path:
    path = tmp_path / "matrix.toml"
    path.write_text(MATRIX, encoding="utf-8")
    return path


def test_solve_cli_emits_plan_without_executing(tmp_path, capsys) -> None:
    code = main(
        (
            "--matrix",
            str(matrix_file(tmp_path)),
            "solve",
            "--want",
            "flash-attn==2.8.3",
            "--target",
            "RTX 4090,driver=560.35,python=3.12,linux",
        )
    )
    captured = capsys.readouterr()
    assert code == 0
    assert "Generated by rigsolve" in captured.out
    assert "pip install" in captured.out
    assert "Executing" not in captured.err


def test_why_cli_returns_unsat_with_explanation(tmp_path, capsys) -> None:
    code = main(
        (
            "--matrix",
            str(matrix_file(tmp_path)),
            "why",
            "flash-attn==2.8.3",
            "--target",
            "RTX 4090,driver=560.35,python=3.13,linux",
        )
    )
    captured = capsys.readouterr()
    assert code == 1
    assert "No solution." in captured.out
    assert "Use Python 3.12" in captured.out


def test_matrix_stats_json(tmp_path, capsys) -> None:
    code = main(("--matrix", str(matrix_file(tmp_path)), "matrix", "stats", "--json"))
    assert code == 0
    assert '"fact_count": 3' in capsys.readouterr().out


def test_invalid_target_is_a_usage_error(tmp_path, capsys) -> None:
    code = main(
        (
            "--matrix",
            str(matrix_file(tmp_path)),
            "solve",
            "--want",
            "torch",
            "--target",
            "gpu=RTX 4090,unknown=value",
        )
    )
    assert code == 64
    assert "unknown target field" in capsys.readouterr().err


@pytest.mark.parametrize("argv", [("solve",), ("check", "--bogus")])
def test_argument_parser_errors_use_the_documented_usage_exit(argv, capsys) -> None:
    assert main(argv) == 64
    assert "error:" in capsys.readouterr().err


def test_invalid_matrix_is_an_expected_domain_error(tmp_path, capsys) -> None:
    invalid = tmp_path / "invalid.toml"
    invalid.write_text("not valid toml = [", encoding="utf-8")
    assert main(("--matrix", str(invalid), "matrix", "stats")) == 1
    assert "invalid matrix TOML" in capsys.readouterr().err


def test_unexpected_failure_uses_stable_internal_exit(monkeypatch, tmp_path, capsys) -> None:
    def fail(*args, **kwargs):
        raise RuntimeError("unexpected test failure")

    monkeypatch.setattr("rigsolve.cli.resolve", fail)
    code = main(
        (
            "--matrix",
            str(matrix_file(tmp_path)),
            "solve",
            "--want",
            "torch",
            "--target",
            "python=3.12,linux",
        )
    )
    assert code == 70
    error = capsys.readouterr().err
    assert "internal error: RuntimeError" in error
    assert "rerun with --debug" in error


def test_invalid_lockfile_is_a_usage_error(tmp_path, capsys) -> None:
    invalid = tmp_path / "invalid-lock.toml"
    invalid.write_text("not_a_lockfile = true\n", encoding="utf-8")

    code = main(("check", "--lockfile", str(invalid)))

    assert code == 64
    assert "invalid lockfile" in capsys.readouterr().err


@pytest.mark.parametrize(
    "extra",
    [
        ("--output", "docker"),
        ("--target", "RTX 4090,driver=580.65,python=3.12,linux"),
        ("--python", "3.12"),
    ],
)
def test_execute_rejects_nonlocal_or_nonpip_plans(extra, monkeypatch, tmp_path, capsys) -> None:
    executed = False

    def forbidden(*args, **kwargs):
        nonlocal executed
        executed = True

    monkeypatch.setattr("rigsolve.cli.execute_plan", forbidden)
    code = main(
        (
            "--matrix",
            str(matrix_file(tmp_path)),
            "solve",
            "--want",
            "torch",
            "--execute",
            *extra,
        )
    )

    assert code == 64
    assert not executed
    assert "--execute" in capsys.readouterr().err
