from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import pytest
from tests.test_resolver import MATRIX

from rigsolve import __version__
from rigsolve.cli import main
from rigsolve.detect import MachineProfile
from rigsolve.matrix import MatrixUpdateResult
from rigsolve.plan import InstallPlan, InstallStep
from rigsolve.solve.resolver import ResolutionOutcome
from rigsolve.verify.smoke import SmokeResult
from rigsolve.verify.tiers import VerificationTier


def matrix_file(tmp_path: Path) -> Path:
    path = tmp_path / "matrix.toml"
    path.write_text(MATRIX, encoding="utf-8")
    return path


def test_module_entrypoint_executes_cli() -> None:
    root = Path(__file__).parents[1]
    result = subprocess.run(
        [sys.executable, "-m", "rigsolve", "--version"],
        cwd=root,
        env={**os.environ, "PYTHONPATH": str(root / "src")},
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 0
    assert result.stdout == f"rigsolve {__version__}\n"
    assert result.stderr == ""


def test_check_docs_rejects_unsupported_arguments() -> None:
    root = Path(__file__).parents[1]
    result = subprocess.run(
        [
            sys.executable,
            str(root / ".github" / "scripts" / "check_docs.py"),
            "--definitely-unsupported",
        ],
        cwd=root,
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 2
    assert "unrecognized arguments: --definitely-unsupported" in result.stderr
    assert "Checked relative links" not in result.stdout


def test_solve_cli_emits_plan_without_executing(tmp_path, capsys) -> None:
    code = main(
        (
            "--matrix",
            str(matrix_file(tmp_path)),
            "solve",
            "--want",
            "flash-attn==2.8.3",
            "--target",
            "RTX 4090,driver=560.35,python=3.12,linux",
        )
    )
    captured = capsys.readouterr()
    assert code == 0
    assert "Generated by rigsolve" in captured.out
    assert "pip install" in captured.out
    assert "Executing" not in captured.err


def test_why_cli_returns_unsat_with_explanation(tmp_path, capsys) -> None:
    code = main(
        (
            "--matrix",
            str(matrix_file(tmp_path)),
            "why",
            "flash-attn==2.8.3",
            "--target",
            "RTX 4090,driver=560.35,python=3.13,linux",
        )
    )
    captured = capsys.readouterr()
    assert code == 1
    assert "No solution." in captured.out
    assert "Use Python 3.12" in captured.out


def test_matrix_stats_json(tmp_path, capsys) -> None:
    code = main(("--matrix", str(matrix_file(tmp_path)), "matrix", "stats", "--json"))
    assert code == 0
    assert '"fact_count": 3' in capsys.readouterr().out


def test_matrix_update_cli_forwards_all_update_options(monkeypatch, tmp_path, capsys) -> None:
    source = matrix_file(tmp_path)
    destination = tmp_path / "updated.toml"
    url = "https://example.test/updated-matrix.toml"
    calls: list[tuple[str, str, Path, bool]] = []

    def fetch(url, *, current, destination, merge):
        calls.append((url, current.matrix_version, destination, merge))
        return MatrixUpdateResult(
            store=current,
            changed=True,
            not_modified=False,
            url=url,
            cache_path=destination,
        )

    monkeypatch.setattr("rigsolve.cli.fetch_update", fetch)

    code = main(
        (
            "--matrix",
            str(source),
            "matrix",
            "update",
            "--url",
            url,
            "--destination",
            str(destination),
            "--no-merge",
        )
    )

    assert code == 0
    assert calls == [(url, "test-1", destination, False)]
    assert capsys.readouterr().out == (f"Matrix updated: test-1 (3 facts)\nCache: {destination}\n")


def test_matrix_update_cli_reports_malformed_url_as_expected_error(tmp_path, capsys) -> None:
    destination = tmp_path / "updated.toml"

    code = main(
        (
            "--matrix",
            str(matrix_file(tmp_path)),
            "matrix",
            "update",
            "--url",
            "not-a-valid-url",
            "--destination",
            str(destination),
            "--no-merge",
        )
    )

    captured = capsys.readouterr()
    assert code == 1
    assert captured.out == ""
    assert "error: cannot fetch matrix update" in captured.err
    assert not destination.exists()


def test_invalid_target_is_a_usage_error(tmp_path, capsys) -> None:
    code = main(
        (
            "--matrix",
            str(matrix_file(tmp_path)),
            "solve",
            "--want",
            "torch",
            "--target",
            "gpu=RTX 4090,unknown=value",
        )
    )
    assert code == 64
    assert "unknown target field" in capsys.readouterr().err


@pytest.mark.parametrize("timeout", ("0", "-1", "nan", "inf"))
def test_verify_rejects_invalid_timeout_as_usage_error(
    timeout, monkeypatch, tmp_path, capsys
) -> None:
    monkeypatch.setattr("rigsolve.cli.detect_machine_profile", MachineProfile)

    code = main(
        (
            "--matrix",
            str(matrix_file(tmp_path)),
            "verify",
            "--package",
            "torch",
            "--timeout",
            timeout,
        )
    )

    assert code == 64
    assert capsys.readouterr().err == "error: --timeout must be a finite positive number\n"


@pytest.mark.parametrize("argv", [("solve",), ("check", "--bogus")])
def test_argument_parser_errors_use_the_documented_usage_exit(argv, capsys) -> None:
    assert main(argv) == 64
    assert "error:" in capsys.readouterr().err


def test_detect_rejects_global_matrix(monkeypatch, tmp_path, capsys) -> None:
    detected = False

    def detect() -> MachineProfile:
        nonlocal detected
        detected = True
        return MachineProfile()

    monkeypatch.setattr("rigsolve.cli.detect_machine_profile", detect)

    code = main(("--matrix", str(tmp_path / "matrix.toml"), "detect"))

    assert code == 64
    assert not detected
    assert "--matrix cannot be used with detect" in capsys.readouterr().err


def test_invalid_matrix_is_an_expected_domain_error(tmp_path, capsys) -> None:
    invalid = tmp_path / "invalid.toml"
    invalid.write_text("not valid toml = [", encoding="utf-8")
    assert main(("--matrix", str(invalid), "matrix", "stats")) == 1
    assert "invalid matrix TOML" in capsys.readouterr().err


def test_unexpected_failure_uses_stable_internal_exit(monkeypatch, tmp_path, capsys) -> None:
    def fail(*args, **kwargs):
        raise RuntimeError("unexpected test failure")

    monkeypatch.setattr("rigsolve.cli.resolve", fail)
    code = main(
        (
            "--matrix",
            str(matrix_file(tmp_path)),
            "solve",
            "--want",
            "torch",
            "--target",
            "python=3.12,linux",
        )
    )
    assert code == 70
    error = capsys.readouterr().err
    assert "internal error: RuntimeError" in error
    assert "rerun with --debug" in error


def test_invalid_lockfile_is_a_usage_error(tmp_path, capsys) -> None:
    invalid = tmp_path / "invalid-lock.toml"
    invalid.write_text("not_a_lockfile = true\n", encoding="utf-8")

    code = main(("check", "--lockfile", str(invalid)))

    assert code == 64
    assert "invalid lockfile" in capsys.readouterr().err


@pytest.mark.parametrize(
    "extra",
    [
        ("--output", "docker"),
        ("--target", "RTX 4090,driver=580.65,python=3.12,linux"),
        ("--python", "3.12"),
    ],
)
def test_execute_rejects_nonlocal_or_nonpip_plans(extra, monkeypatch, tmp_path, capsys) -> None:
    executed = False

    def forbidden(*args, **kwargs):
        nonlocal executed
        executed = True

    monkeypatch.setattr("rigsolve.cli.execute_plan", forbidden)
    code = main(
        (
            "--matrix",
            str(matrix_file(tmp_path)),
            "solve",
            "--want",
            "torch",
            "--execute",
            *extra,
        )
    )

    assert code == 64
    assert not executed
    assert "--execute" in capsys.readouterr().err


@pytest.mark.parametrize("option", ("--target", "--python"))
def test_execute_rejects_empty_target_overrides(option, monkeypatch, tmp_path, capsys) -> None:
    plan = InstallPlan(
        requested=("torch",),
        steps=(InstallStep(package="torch", version="2.9.0"),),
        matrix_version="test",
        matrix_digest="a" * 64,
    )
    executed = False

    def forbidden(*args, **kwargs):
        nonlocal executed
        executed = True

    monkeypatch.setattr("rigsolve.cli.execute_plan", forbidden)
    monkeypatch.setattr("rigsolve.cli._profile", lambda *args: MachineProfile())
    monkeypatch.setattr(
        "rigsolve.cli.resolve", lambda *args, **kwargs: ResolutionOutcome(plan=plan)
    )
    code = main(
        (
            "--matrix",
            str(matrix_file(tmp_path)),
            "solve",
            "--want",
            "torch",
            "--execute",
            "--skip-verify",
            option,
            "",
        )
    )

    assert code == 64
    assert not executed
    assert f"argument {option}: value must not be empty" in capsys.readouterr().err


@pytest.mark.parametrize(("verification_ok", "expected_code"), ((True, 0), (False, 2)))
def test_execute_runs_post_install_verification_by_default(
    verification_ok, expected_code, monkeypatch, tmp_path, capsys
) -> None:
    plan = InstallPlan(
        requested=("torch",),
        steps=(InstallStep(package="torch", version="2.9.0", tier=0),),
        matrix_version="test",
        matrix_digest="a" * 64,
    )
    executed: list[InstallPlan] = []
    verified: list[tuple[str, ...]] = []

    monkeypatch.setattr("rigsolve.cli._profile", lambda *args: MachineProfile())
    monkeypatch.setattr(
        "rigsolve.cli.resolve", lambda *args, **kwargs: ResolutionOutcome(plan=plan)
    )
    monkeypatch.setattr("rigsolve.cli.execute_plan", lambda value, **kwargs: executed.append(value))

    def verify(packages, **kwargs):
        verified.append(tuple(packages))
        return (
            SmokeResult(
                "torch",
                verification_ok,
                VerificationTier.RUNS if verification_ok else None,
                version="2.9.0" if verification_ok else None,
                error=None if verification_ok else "probe failed",
            ),
        )

    monkeypatch.setattr("rigsolve.cli.verify_packages", verify)

    code = main(
        (
            "--matrix",
            str(matrix_file(tmp_path)),
            "solve",
            "--want",
            "torch",
            "--execute",
        )
    )

    assert code == expected_code
    assert executed == [plan]
    assert verified == [("torch",)]
    error = capsys.readouterr().err
    assert "Post-install verification" in error
    assert ("GPU-tested" if verification_ok else "[FAIL]") in error


def test_skip_verify_requires_execute(tmp_path, capsys) -> None:
    code = main(
        (
            "--matrix",
            str(matrix_file(tmp_path)),
            "solve",
            "--want",
            "torch",
            "--skip-verify",
        )
    )

    assert code == 64
    assert "valid only with --execute" in capsys.readouterr().err
