from __future__ import annotations

from rigsolve.errors import UserInputError
from rigsolve.plan.emit.pip import emit_pip
from rigsolve.plan.install import InstallPlan


def emit_colab(plan: InstallPlan) -> str:
    platform = str(plan.target.get("platform", "linux")).lower()
    if not platform.startswith("linux"):
        raise UserInputError("Colab output requires a Linux target")
    header = "%%bash\n# Colab bootstrap generated by rigsolve. Run this as one code cell.\n"
    return header + emit_pip(plan)
