from __future__ import annotations

import shlex

from rigsolve.plan.install import InstallPlan, InstallStep


def pip_command(step: InstallStep) -> str:
    parts = ["python", "-m", "pip", "install"]
    if step.index_url:
        parts.extend(("--index-url", step.index_url))
    parts.extend(step.flags)
    parts.append(step.requirement)
    return " ".join(shlex.quote(part) for part in parts)


def emit_pip(plan: InstallPlan) -> str:
    lines = [
        "# Generated by rigsolve; review before running.",
        f"# Matrix {plan.matrix_version} ({plan.matrix_digest[:12]}); weakest evidence: tier {plan.weakest_tier}.",
    ]
    for warning in plan.warnings:
        lines.append(f"# WARNING: {warning}")
    for step in plan.ordered_steps():
        if step.source_build:
            estimate = step.build_estimate or "duration depends on hardware"
            guidance = [estimate]
            if step.ram_gb_per_job is not None:
                guidance.append(f"~{step.ram_gb_per_job:g} GiB RAM per compiler job")
            lines.append(f"# SOURCE BUILD: {step.package} ({'; '.join(guidance)}).")
            if step.build_requirements:
                requirements = " ".join(
                    shlex.quote(requirement) for requirement in step.build_requirements
                )
                lines.append(f"python -m pip install {requirements}")
        for name, value in step.environment:
            lines.append(f"export {name}={shlex.quote(value)}")
        lines.append(pip_command(step))
    return "\n".join(lines) + "\n"
