from __future__ import annotations

from urllib.parse import urlparse

from packaging.version import InvalidVersion, Version

from rigsolve.errors import UserInputError
from rigsolve.plan.emit._common import toml_string
from rigsolve.plan.install import InstallPlan


def _index_name(url: str) -> str:
    path = urlparse(url).path.rstrip("/").split("/")[-1] or "gpu"
    safe = "".join(character if character.isalnum() else "-" for character in path.lower())
    return f"rigsolve-{safe.strip('-')}"


def emit_uv(plan: InstallPlan) -> str:
    if any(step.source_build for step in plan.steps):
        raise UserInputError(
            "uv project output cannot faithfully encode this source build; use pip, TOML, JSON, or Docker output"
        )
    steps = plan.ordered_steps()
    python_constraint = ">=3.10"
    target_python = plan.target.get("python_version")
    if isinstance(target_python, str):
        try:
            release = Version(target_python).release
        except InvalidVersion:
            release = ()
        if len(release) >= 2:
            python_constraint = f"=={release[0]}.{release[1]}.*"
    lines = [
        "# Generated by rigsolve; merge this snippet into pyproject.toml.",
        "[project]",
        'name = "gpu-environment"',
        'version = "0.0.0"',
        f"requires-python = {toml_string(python_constraint)}",
        "dependencies = [",
    ]
    lines.extend(f"  {toml_string(f'{step.package}=={step.version}')}," for step in steps)
    lines.append("]")

    indexes: dict[str, str] = {}
    for step in steps:
        if step.index_url:
            indexes.setdefault(step.index_url, _index_name(step.index_url))
    for url, name in sorted(indexes.items()):
        lines.extend(
            (
                "",
                "[[tool.uv.index]]",
                f"name = {toml_string(name)}",
                f"url = {toml_string(url)}",
                "explicit = true",
            )
        )

    sources: list[str] = []
    for step in steps:
        if step.artifact_url:
            sources.append(f"{step.package} = {{ url = {toml_string(step.requirement)} }}")
        elif step.index_url:
            sources.append(f"{step.package} = {{ index = {toml_string(indexes[step.index_url])} }}")
    if sources:
        lines.extend(("", "[tool.uv.sources]", *sources))
    return "\n".join(lines) + "\n"
