"""Safe, import-free detection of local and hypothetical CUDA environments."""

from .driver import (
    driver_supports_runtime,
    driver_to_max_cuda,
    max_cuda_for_driver,
    max_cuda_runtime_for_driver,
)
from .gpu import (
    GPUProbeResult,
    compute_capability_from_name,
    detect_gpu,
    detect_gpus,
    parse_nvidia_smi_csv,
)
from .installed import (
    InstalledProbeResult,
    canonicalize_package_name,
    detect_installed,
    detect_installed_packages,
    inspect_torch_distribution,
    parse_build_markers,
)
from .model import (
    CudaToolkit,
    DetectionIssue,
    DriverInfo,
    GPUDevice,
    GpuDevice,
    InstalledEnvironment,
    InstalledPackage,
    MachineProfile,
    PlatformInfo,
    ProfileValidationError,
    TorchBuild,
    normalise_compute_capability,
)
from .platform import (
    PlatformProbeResult,
    derive_manylinux_tag,
    detect_container_runtime,
    detect_platform,
    detect_wsl,
    normalize_architecture,
    normalize_os,
    parse_glibc_version,
)
from .profile import collect_machine_profile, detect_machine_profile, detect_profile
from .target import (
    TargetParseError,
    TargetSpec,
    apply_target,
    parse_target,
    parse_target_string,
    profile_from_target,
)
from .toolkit import (
    ToolkitProbeResult,
    detect_nvcc,
    detect_toolkit,
    parse_nvcc_output,
)

__all__ = [
    "CudaToolkit",
    "DetectionIssue",
    "DriverInfo",
    "GPUDevice",
    "GPUProbeResult",
    "GpuDevice",
    "InstalledEnvironment",
    "InstalledPackage",
    "InstalledProbeResult",
    "MachineProfile",
    "PlatformInfo",
    "PlatformProbeResult",
    "ProfileValidationError",
    "TargetParseError",
    "TargetSpec",
    "ToolkitProbeResult",
    "TorchBuild",
    "apply_target",
    "canonicalize_package_name",
    "collect_machine_profile",
    "compute_capability_from_name",
    "derive_manylinux_tag",
    "detect_container_runtime",
    "detect_gpu",
    "detect_gpus",
    "detect_installed",
    "detect_installed_packages",
    "detect_machine_profile",
    "detect_nvcc",
    "detect_platform",
    "detect_profile",
    "detect_toolkit",
    "detect_wsl",
    "driver_supports_runtime",
    "driver_to_max_cuda",
    "inspect_torch_distribution",
    "max_cuda_for_driver",
    "max_cuda_runtime_for_driver",
    "normalise_compute_capability",
    "normalize_architecture",
    "normalize_os",
    "parse_build_markers",
    "parse_glibc_version",
    "parse_nvcc_output",
    "parse_nvidia_smi_csv",
    "parse_target",
    "parse_target_string",
    "profile_from_target",
]
